### ISSUE TITLE
Defect-Click 如何使用？

### ISSUE THREAD

**Issue by xuyu666** [EnVision-Research/Defect_Spectrum#1]
您好，看到您的文章感觉很有帮助，其中对文章中提到的缺陷掩码标注工具比较感兴趣，想了解一下如何来调用或者使用它？同时，这个工具它是基于SAM模型微调的么？<惊讶>

**Comment by AndysonYs** [comment]
您好，DefectClick不是基于SAM的，它是基于FocalClick工作的改进，修改了其中的crop方式和loss，详见文章Section3.4。DefectClick使用了21个思谋科技私有的工业大数据集，因此，我们不会直接release这个模型。您可以根据文章中的结构修改，在自有数据上尝试训练。

但是，DefectSpectrum中的数据集，合成数据，生成数据代码，均已开源，欢迎您使用。
