### ISSUE TITLE
dataset download

### ISSUE THREAD

**Issue by egbertYeah** [EnVision-Research/Defect_Spectrum#5]
hello， thanks for you work. can you upload dataset to google drive or baidu yun pan? it's hard to download data from huggingface.

**Comment by AndysonYs** [comment]
Hi! Uploading all the data again is a little bit demanding. You may download our dataset by using git lfs on huggingface. Did you meet any problem when download it? Maybe we can help you with it.

**Comment by dswahu** [comment]
我在hf-mirror 使用hfd工具下载，一张张图片下载，下载过程非常容易中断，已经下载一天了，才下载了一点点，能不能直接使用上次数据集的压缩包啊

**Comment by AndysonYs** [comment]
@dswahu 那请稍等哈，我们准备一下

**Comment by egbertYeah** [comment]
> Hi! Uploading all the data again is a little bit demanding. You may download our dataset by using git lfs on huggingface. Did you meet any problem when download it? Maybe we can help you with it.

我可以使用git lfs下载数据，但是得到的图片内容大小是错误的，我对比了一下size，下载的应该是图像的指针内容

**Comment by AndysonYs** [comment]
> > Hi! Uploading all the data again is a little bit demanding. You may download our dataset by using git lfs on huggingface. Did you meet any problem when download it? Maybe we can help you with it.
> 
> 我可以使用git lfs下载数据，但是得到的图片内容大小是错误的，我对比了一下size，下载的应该是图像的指针内容

是的，这样下载后还需要pull一次，具体你要搜下hf的下载教程

**Comment by AndysonYs** [comment]
@egbertYeah @dswahu https://drive.google.com/file/d/1Jgy4-68F8Xj16tNHzgBoDwRlsKvm92Sf/view?usp=sharing

这个是压缩包google drive链接

**Comment by dswahu** [comment]
> @egbertYeah @dswahu https://drive.google.com/file/d/1Jgy4-68F8Xj16tNHzgBoDwRlsKvm92Sf/view?usp=sharing
> 
> 这个是压缩包google drive链接

谢谢

**Comment by AndysonYs** [comment]
> > @egbertYeah @dswahu https://drive.google.com/file/d/1Jgy4-68F8Xj16tNHzgBoDwRlsKvm92Sf/view?usp=sharing
> > 这个是压缩包google drive链接
> 
> 谢谢

不客气

**Comment by congyao123456** [comment]
> 我在hf-mirror使用hfd工具下载，一张张图片下载，下载过程非常容易中断，已经下载一天了，才下载了一点点，能不能直接上传数据集的压缩包啊

我也是同样的问题，请问是否有下载好的数据集，百度网盘或者其他形式分享一下
