### ISSUE TITLE
pretrained checkpoint

### ISSUE THREAD

**Issue by egbertYeah** [EnVision-Research/Defect_Spectrum#6]
for defeat-gen, can you provide some checkpoint for test?

**Comment by AndysonYs** [comment]
Sure, I will give you the DS-mvtec-cable as an example.

**Comment by egbertYeah** [comment]
https://github.com/EnVision-Research/Defect_Spectrum/blob/a9b83c38bcd0afc9028677cf44825c2ac7d9bdca/config/large_recep.yml#L30，这个里面不需要加载预训练权重吗？如果需要，麻烦提供一下，谢谢

**Comment by AndysonYs** [comment]
你好，这个是训练脚本，不需要加载pretrained weight，空着就可以

**Comment by egbertYeah** [comment]
@AndysonYs 非常感谢

**Comment by AndysonYs** [comment]
> @AndysonYs 非常感谢

不客气。
