### ISSUE TITLE
数据集划分以及分割模型有关问题

### ISSUE THREAD

**Issue by LHT-HUST** [EnVision-Research/Defect_Spectrum#7]
你好，我很喜欢你们的提出的bencnmark，我想了解一下论文里训练分割模型时（仅使用原图/使用生成图像）时的训练集和验证集，测试集的划分情况，是按照固定比例或者固定数量划分或者其他的划分方式，方便的话麻烦详细介绍一下

**Comment by LHT-HUST** [comment]
还有一个问题是论文中使用的分割模型是follow各个模型官方代码嘛，或者是使用了mmseg中集成的版本，方便的话帮忙解答一下

**Comment by AndysonYs** [comment]
> 你好，我很喜欢你们的提出的bencnmark，我想了解一下论文里训练分割模型时（仅使用原图/使用生成图像）时的训练集和验证集，测试集的划分情况，是按照固定比例或者固定数量划分或者其他的划分方式，方便的话麻烦详细介绍一下

你好，感谢你的关注。对于defect-spectrum-VISION，我们直接沿用了VISION dataset的划分。对于其他三个subsets，他们本身没有划分，所以我们把每个缺陷类别（请注意是缺陷类别，不是物体类别）的前5张图作为training set，其他图作为val set。

**Comment by AndysonYs** [comment]
> 还有一个问题是论文中使用的分割模型是follow各个模型官方代码嘛，或者是使用了mmseg中集成的版本，方便的话帮忙解答一下

文章中使用的分割结果来自于思谋科技的工具链代码库。该代码库与mmseg做过性能对齐，在主流分割数据集，模型上表现均与mmseg基本一致。你可以使用mmseg来做实验。

**Comment by LHT-HUST** [comment]
好的，感谢解答！
